# Bitnami MongoDB StatefulSet overrides
# See cloud_INFRASTRUCTURE.md § Database (MongoDB) Deployment
architecture: standalone
auth:
  existingSecret: mongodb-admin
persistence:
  storageClass: gp3
  size: 50Gi
tolerations:
  - key: workload
    value: stateful
    effect: NoSchedule
nodeSelector:
  workload: stateful
