replicaCount: 3

image:
  repository: ghcr.io/wolfy5786/sourcing
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

env:
  - name: RABBITMQ_URL
    valueFrom:
      secretKeyRef:
        name: sourcing-secrets
        key: rabbitmq-url
  - name: MONGO_URI
    valueFrom:
      secretKeyRef:
        name: sourcing-secrets
        key: mongo-uri
  - name: REDIS_URL
    valueFrom:
      secretKeyRef:
        name: sourcing-secrets
        key: redis-url
  - name: API_RATE_LIMIT
    value: "2.0"
  - name: MAX_RETRIES
    value: "3"
  - name: ENABLE_YC
    value: "true"
  - name: ENABLE_HN
    value: "true"
  - name: ENABLE_PH
    value: "false"
