/** All drafts across every campaign in one table. */

import { useMemo, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { useQueries, useQuery } from "@tanstack/react-query";
import { Mail, Search } from "lucide-react";

import { endpoints } from "@/api/endpoints";
import type { Draft, DraftStatus } from "@/api/types";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { timeAgo } from "@/lib/format";

type DraftRow = Draft & { campaign_name: string };

const STATUS_LABEL: Record<DraftStatus, string> = {
  generating: "Generating",
  draft_created: "Ready",
  failed: "Failed",
};

const STATUS_VARIANT: Record<DraftStatus, "warning" | "success" | "destructive"> = {
  generating: "warning",
  draft_created: "success",
  failed: "destructive",
};

export default function DraftsList() {
  const [params, setParams] = useSearchParams();
  const campaignFilter = params.get("campaign") ?? "";
  const statusFilter = (params.get("status") ?? "") as DraftStatus | "";
  const [search, setSearch] = useState("");

  const campaignsQuery = useQuery({
    queryKey: ["campaigns"],
    queryFn: () => endpoints.listCampaigns(),
  });

  const draftQueries = useQueries({
    queries: (campaignsQuery.data ?? []).map((c) => ({
      queryKey: ["campaign-drafts", c.id],
      queryFn: () => endpoints.listCampaignDrafts(c.id),
      enabled: !!campaignsQuery.data,
    })),
  });

  const allRows: DraftRow[] = useMemo(() => {
    if (!campaignsQuery.data) return [];
    return campaignsQuery.data.flatMap((c, i) =>
      (draftQueries[i]?.data ?? []).map((d) => ({
        ...d,
        campaign_name: c.name,
      })),
    );
  }, [campaignsQuery.data, draftQueries]);

  const rows = useMemo(() => {
    return allRows.filter((d) => {
      if (campaignFilter && d.campaign_id !== campaignFilter) return false;
      if (statusFilter && d.status !== statusFilter) return false;
      if (!search) return true;
      const q = search.toLowerCase();
      return (
        d.subject.toLowerCase().includes(q) ||
        d.body.toLowerCase().includes(q)
      );
    });
  }, [allRows, campaignFilter, statusFilter, search]);

  const isLoading =
    campaignsQuery.isLoading || draftQueries.some((q) => q.isLoading);

  function setFilter(k: string, v: string | null) {
    const next = new URLSearchParams(params);
    if (v) next.set(k, v);
    else next.delete(k);
    setParams(next);
  }

  return (
    <div>
      <div>
        <h1 className="text-3xl font-semibold tracking-tight">Drafts</h1>
        <p className="mt-2 text-black/60">
          Every personalized cold email generated by the pipeline.
        </p>
      </div>

      <div className="mt-6 flex items-center gap-3 flex-wrap">
        <div className="relative flex-1 min-w-[240px]">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 size-4 text-black/40" />
          <Input
            placeholder="Search subject or body"
            className="pl-9"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
        </div>
        <select
          value={campaignFilter}
          onChange={(e) => setFilter("campaign", e.target.value || null)}
          className="h-10 rounded-md border border-black/10 bg-white px-3 text-sm"
        >
          <option value="">All campaigns</option>
          {campaignsQuery.data?.map((c) => (
            <option key={c.id} value={c.id}>
              {c.name}
            </option>
          ))}
        </select>
        <select
          value={statusFilter}
          onChange={(e) => setFilter("status", e.target.value || null)}
          className="h-10 rounded-md border border-black/10 bg-white px-3 text-sm"
        >
          <option value="">All statuses</option>
          <option value="generating">Generating</option>
          <option value="draft_created">Ready</option>
          <option value="failed">Failed</option>
        </select>
      </div>

      <div className="mt-6 space-y-2">
        {isLoading && (
          <>
            {[0, 1, 2].map((i) => (
              <Skeleton key={i} className="h-24 w-full" />
            ))}
          </>
        )}

        {!isLoading && rows.length === 0 && (
          <div className="rounded-xl border border-dashed border-black/15 p-12 text-center text-black/40">
            <Mail className="mx-auto size-8 text-black/20" />
            <div className="mt-3">No drafts matched.</div>
          </div>
        )}

        {rows.map((d) => (
          <Link
            key={d.id}
            to={`/app/drafts/${d.id}`}
            className="block rounded-xl border border-black/10 bg-white p-5 hover:border-black/30 transition-colors"
          >
            <div className="flex items-center justify-between gap-3 flex-wrap">
              <div className="flex items-center gap-3 min-w-0">
                <Badge variant={STATUS_VARIANT[d.status]}>
                  {STATUS_LABEL[d.status]}
                </Badge>
                <h3 className="font-medium truncate">{d.subject}</h3>
              </div>
              <div className="text-xs text-black/40 shrink-0">
                {timeAgo(d.generated_at)} · {d.campaign_name}
              </div>
            </div>
            <p className="mt-3 text-sm text-black/60 line-clamp-2">{d.body}</p>
            {d.personalization_hooks.length > 0 && (
              <div className="mt-3 flex flex-wrap gap-1.5">
                {d.personalization_hooks.map((h) => (
                  <Badge key={h} variant="outline">
                    {h}
                  </Badge>
                ))}
              </div>
            )}
          </Link>
        ))}
      </div>
    </div>
  );
}
