/** All drafts across every campaign in one table. */

import { useMemo, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { useQueries, useQuery } from "@tanstack/react-query";
import { motion } from "framer-motion";
import { Mail, Search } from "lucide-react";

import { endpoints } from "@/api/endpoints";
import type { Draft, DraftStatus } from "@/api/types";
import { Avatar } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { EmptyState } from "@/components/ui/empty-state";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { timeAgo } from "@/lib/format";

type DraftRow = Draft & { campaign_name: string };

const STATUS_LABEL: Record<DraftStatus, string> = {
  generating: "Generating",
  draft_created: "Ready",
  failed: "Failed",
};

const STATUS_VARIANT: Record<DraftStatus, "warning" | "success" | "destructive"> = {
  generating: "warning",
  draft_created: "success",
  failed: "destructive",
};

export default function DraftsList() {
  const [params, setParams] = useSearchParams();
  const campaignFilter = params.get("campaign") ?? "";
  const statusFilter = (params.get("status") ?? "") as DraftStatus | "";
  const [search, setSearch] = useState("");

  const campaignsQuery = useQuery({
    queryKey: ["campaigns"],
    queryFn: () => endpoints.listCampaigns(),
  });

  const draftQueries = useQueries({
    queries: (campaignsQuery.data ?? []).map((c) => ({
      queryKey: ["campaign-drafts", c.id],
      queryFn: () => endpoints.listCampaignDrafts(c.id),
      enabled: !!campaignsQuery.data,
    })),
  });

  const allRows: DraftRow[] = useMemo(() => {
    if (!campaignsQuery.data) return [];
    return campaignsQuery.data.flatMap((c, i) =>
      (draftQueries[i]?.data ?? []).map((d) => ({
        ...d,
        campaign_name: c.name,
      })),
    );
  }, [campaignsQuery.data, draftQueries]);

  const rows = useMemo(() => {
    return allRows.filter((d) => {
      if (campaignFilter && d.campaign_id !== campaignFilter) return false;
      if (statusFilter && d.status !== statusFilter) return false;
      if (!search) return true;
      const q = search.toLowerCase();
      return (
        d.subject.toLowerCase().includes(q) ||
        d.body.toLowerCase().includes(q)
      );
    });
  }, [allRows, campaignFilter, statusFilter, search]);

  const isLoading =
    campaignsQuery.isLoading || draftQueries.some((q) => q.isLoading);

  function setFilter(k: string, v: string | null) {
    const next = new URLSearchParams(params);
    if (v) next.set(k, v);
    else next.delete(k);
    setParams(next);
  }

  return (
    <div>
      <div>
        <h1 className="text-3xl font-semibold tracking-tight">Drafts</h1>
        <p className="mt-2 text-black/60">
          Every personalized cold email generated by the pipeline.
        </p>
      </div>

      <div className="mt-6 flex items-center gap-3 flex-wrap">
        <div className="relative flex-1 min-w-[240px]">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 size-4 text-black/40" />
          <Input
            placeholder="Search subject or body"
            className="pl-9"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
        </div>
        <select
          value={campaignFilter}
          onChange={(e) => setFilter("campaign", e.target.value || null)}
          className="h-10 rounded-md border border-black/10 bg-white px-3 text-sm"
        >
          <option value="">All campaigns</option>
          {campaignsQuery.data?.map((c) => (
            <option key={c.id} value={c.id}>
              {c.name}
            </option>
          ))}
        </select>
        <select
          value={statusFilter}
          onChange={(e) => setFilter("status", e.target.value || null)}
          className="h-10 rounded-md border border-black/10 bg-white px-3 text-sm"
        >
          <option value="">All statuses</option>
          <option value="generating">Generating</option>
          <option value="draft_created">Ready</option>
          <option value="failed">Failed</option>
        </select>
      </div>

      <div className="mt-6 rounded-xl border border-black/10 bg-white overflow-hidden">
        {isLoading && (
          <div className="p-3 space-y-2">
            {[0, 1, 2].map((i) => (
              <Skeleton key={i} className="h-16 w-full" />
            ))}
          </div>
        )}

        {!isLoading && rows.length === 0 && (
          <EmptyState
            icon={<Mail className="size-5" />}
            title="No drafts matched"
            description={
              search || statusFilter || campaignFilter
                ? "Try clearing your filters or search."
                : "Drafts will appear here as the messaging stage produces them."
            }
          />
        )}

        {!isLoading && rows.length > 0 && (
          <ul className="divide-y divide-black/5">
            {rows.map((d, i) => {
              const recipient = d.recipient;
              const recipientName = recipient?.name ?? "Unknown recipient";
              const senderLine = [
                recipientName,
                recipient?.company && `· ${recipient.company}`,
              ]
                .filter(Boolean)
                .join(" ");
              return (
                <motion.li
                  key={d.id}
                  initial={{ opacity: 0, y: 4 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{
                    delay: Math.min(i * 0.025, 0.4),
                    duration: 0.25,
                  }}
                >
                  <Link
                    to={`/app/drafts/${d.id}`}
                    className="flex items-center gap-4 px-5 py-4 hover:bg-black/[0.02] transition-colors"
                  >
                    <Avatar
                      name={recipient?.name ?? undefined}
                      domain={recipient?.company_domain ?? undefined}
                      size={40}
                    />
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2">
                        <span className="font-medium truncate">
                          {senderLine || "Unknown recipient"}
                        </span>
                        <Badge variant={STATUS_VARIANT[d.status]}>
                          {STATUS_LABEL[d.status]}
                        </Badge>
                      </div>
                      <div className="mt-0.5 text-sm text-black/80 truncate">
                        <span className="font-medium">{d.subject}</span>
                        <span className="text-black/40"> — </span>
                        <span className="text-black/50">{d.body}</span>
                      </div>
                      <div className="mt-0.5 text-xs text-black/40 truncate">
                        {d.campaign_name}
                      </div>
                    </div>
                    <div className="text-xs text-black/40 shrink-0 tabular-nums">
                      {timeAgo(d.generated_at)}
                    </div>
                  </Link>
                </motion.li>
              );
            })}
          </ul>
        )}
      </div>
    </div>
  );
}
